#!/bin/bash
# NanoHUB SecurityInfo
source /opt/nanohub/environment.sh
CMD_UUID=$(uuidgen)

curl -u "nanohub:${NANOHUB_API_KEY}" \
  -X PUT http://localhost:9004/api/v1/nanomdm/enqueue/$1 \
  --data-binary @- << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"\>
<plist version="1.0">
<dict>
    <key>Command</key>
    <dict>
        <key>RequestType</key>
        <string>SecurityInfo</string>
    </dict>
    <key>CommandUUID</key>
    <string>$CMD_UUID</string>
</dict>
</plist>
EOF
